### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by LouisYZK** [cyZhu98/depression_papers#1]
小哥你好~，看你也在关注AVec2019-DDS, 咋样 Baseline 可否能复现呢？
我最近在尝试复现他们的baseline和top结果的文章，发现跟作者结果不太一致。

Hi dude, see you are watching for AVEC2019-DDS as well, have you been tring on the implemention of the baseline paper?
I've tried, but my results are different from the ori authors'. ...

**Comment by cyZhu98** [comment]
没有哦，这个数据集规模太小了，网络复杂点的话结果会动荡地比较厉害~要复现原结果还是比较困难的，另外好多工作都是取验证集最高的结果（竞赛一般这么搞），指不定是各种调参，改seed之类的做法

**Comment by LouisYZK** [comment]
> 没有哦，这个数据集规模太小了，网络复杂点的话结果会动荡地比较厉害~要复现原结果还是比较困难的，另外好多工作都是取验证集最高的结果（竞赛一般这么搞），指不定是各种调参，改seed之类的做法

OK,fine. 谢谢分享。我再看看。
